### ISSUE TITLE
[Warning] integer conversion resulted in a change of sign

### ISSUE THREAD

**Issue by ChayMa19** [BlackBrickOrg/tiny-coap#2]
Hello, 

While ompiling the library I had integer conversion resulted in a change of sign warning.
in this line : 
     if (TCOAP_CHECK_RESP(resp_mask, TCOAP_RESP_INVALID_PACKET)) 
Don't know if I cast the TCOAP_RESP_INVALID_PACKET to unsigned int will affect the functionality ? 
Could anyone help please ? 

best regards,

**Comment by SergeMaslyakov** [comment]
Hi

I use it for 32-b mcu's and didn't see this warning.

And I don't exactly but looks like it shouldn't affect functionality if we change it this way:

file 
```
TCOAP_RESP_INVALID_PACKET   = (int) 0x80000000
```

to 

```
TCOAP_RESP_INVALID_PACKET   = (uint32_t) 0x80000000
```

**Comment by ChayMa19** [comment]
Thank you for your answer,  I have solved the problem.
By the way, I have other question.
Why there is no link between the tcopa_rx_packet function and the HW read like the tcoap_tx_data function?

**Comment by SergeMaslyakov** [comment]
Hi.

`tcoap_tx_data` - you should implement it according to your hardware.
`tcoap_rx_packet` / `tcoap_rx_byte` - you should use it inside your host-code, e.g. in `interrupt_handler` or similar.

There is some example [https://github.com/BlackBrickOrg/tiny-coap/wiki/External-interface-implementation](https://github.com/BlackBrickOrg/tiny-coap/wiki/External-interface-implementation)

**Comment by ChayMa19** [comment]
Thank your for your answer. 
1- How aout the callback function which dedicated to get the response from the server I think it will only get what have been read in the interrupt_handler  function?
2- Do you have some server example that I can use to test ur library ?
Thank you ^^

**Comment by SergeMaslyakov** [comment]
```
extern tcoap_error tcoap_wait_event(tcoap_handle * const handle, const uint32_t timeout_ms);
```
some example
[https://github.com/BlackBrickOrg/tiny-coap/wiki/Block-wise-mode-example](https://github.com/BlackBrickOrg/tiny-coap/wiki/Block-wise-mode-example)


Server

Just example [https://github.com/Mozilla9/coap-iot-server](https://github.com/Mozilla9/coap-iot-server)

Server for coap on Java: [https://github.com/eclipse/californium](https://github.com/eclipse/californium)

**Comment by ChayMa19** [comment]
Thank you so much for the help ^^
